# --- Stage 1: Build dependencies and node_modules ---
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Install necessary build dependencies
RUN apk add --no-cache python3 make g++

# Copy package files and tsconfig
COPY package*.json tsconfig.json ./

# Copy scripts and data
COPY scripts ./scripts
COPY .db ./.db

# Install dependencies
RUN npm install
RUN npm install --save-dev @types/mongoose

# --- Stage 2: Final lightweigh Image ---
FROM node:18-alpine

# Create a Non-Root user and Group
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Set working directory
WORKDIR /app

# Copy node_modules and scripts from builder
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/scripts ./scripts
COPY --from=builder /app/.db ./.db
COPY --from=builder /app/tsconfig.json ./tsconfig.json

# Set environment variables
ENV NODE_ENV=development

# Change ownership (optional, safer)
RUN chown -R appuser:appgroup /app

# Switch to non-root user
USER appuser

# Command to run migration
CMD ["npx", "ts-node", "--project", "scripts/tsconfig.json", "scripts/migrate-data.ts"]
